- examples/allow_clippy/Cargo.toml
- examples/clippy/Cargo.toml
- examples/env_literal/Cargo.toml
- examples/path_separator_in_string_literal/Cargo.toml
- examples/question_mark_in_expression/Cargo.toml
- utils/testing/Cargo.toml
The driver builder uses a remote `dylint_driver` package if building in release mode or if `dylint_driver_remote` is enabled.
https://github.com/smoelius/dylint/blob/844a3ab339d0dcf69102044368b1bbd907b45787/dylint/src/driver_builder.rs#L112-L113
So when `dylint_testing` is built in debug mode, it looks for a local `dylint_driver` package and cannot find one.
A solution is to have `dylint_testing` enable the `dylint_driver_remote` feature by default.
I think I would prefer the feature be `dylint_driver_local`, but this solves the immediate problem.
> Fetch remote `dylint_driver` in `dylint_testing` by default

- cargo-dylint/Cargo.toml
- cargo-dylint/tests/list.rs
- dylint/Cargo.toml
- dylint/src/driver_builder.rs
- examples/allow_clippy/Cargo.toml
- examples/clippy/Cargo.toml
- examples/env_literal/Cargo.toml
- examples/path_separator_in_string_literal/Cargo.toml
- examples/question_mark_in_expression/Cargo.toml
- utils/testing/Cargo.toml
This change is necessary because a crate graph only gets one copy of a dependency.
> `dylint_driver_remote` -> `dylint_driver_local`

- cargo-dylint/tests/metadata.rs
- cargo-dylint/tests/warn.rs
- driver/.cargo/config.toml
- driver/Cargo.toml
- dylint/src/lib.rs
- dylint/src/metadata.rs
- examples/allow_clippy/.cargo/config.toml
- examples/allow_clippy/Cargo.toml
- examples/clippy/.cargo/config.toml
- examples/clippy/Cargo.toml
- examples/clippy/tests/ui.rs
- examples/env_literal/.cargo/config.toml
- examples/env_literal/Cargo.toml
- examples/path_separator_in_string_literal/.cargo/config.toml
- examples/path_separator_in_string_literal/Cargo.toml
- examples/question_mark_in_expression/.cargo/config.toml
- examples/question_mark_in_expression/Cargo.toml
- examples/try_io_result/.cargo/config.toml
- examples/try_io_result/Cargo.toml
- internal/src/cargo.rs
- internal/src/env.rs
- internal/src/testing.rs
- scripts/lint.sh
- utils/testing/src/lib.rs
This has numerous benefits:
* Build times are faster, because all of the workspaces share a `deps` directory.
* `cargo clean` now works.
* It simplifies the script used to lint the repository.
Thanks to @thomaseizinger for showing us this was possible.
> Have all workspaces share a target directory

- dylint/src/driver_builder.rs
- internal/src/env.rs
In #43 one of the fixes was to copy Libraries to the Driver Folder.
This PR instead provides those Libraries by adding them to the Path that's supplied when determining the Driver Version.
This doesn't have to be merged, its just an alternate Solution I wanted to bring up.
> Add Toolchain Folder to Path, instead of copying dll's.

- Cargo.lock
- cargo-dylint/Cargo.toml
- cargo-dylint/src/main.rs
- examples/allow_clippy/Cargo.lock
- examples/allow_clippy/Cargo.toml
- examples/allow_clippy/rust-toolchain
- examples/allow_clippy/src/allow_clippy.rs
- scripts/toolchain_from_version.sh
The latest update of Clap breaks the installation of cargo-dylint ([Concrete Case](https://github.com/trailofbits/dylint-template/pull/6/checks?check_run_id=3333730574)).
The problem was fixed by removing the `multiple = true,` inside the derive annotations.
I also pinned the clap dependency to avoid further breakage. (Cargo sees Beta releases as Semver compatible)
A downside to the move to Clap `3.0.0-beta.4` is that it uses the [Attributes can invoke function-like macros](https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#attributes-can-invoke-function-like-macros) Feature of Rust 1.54, which prevents the `allow-clippy` Lint from linting cargo-dylint correctly.
Either `allow-clippy` should be moved to a more recent rust version or pin clap to `3.0.0-beta.2` instead.
> Fix Clap Dependency

- utils/linting/src/lib.rs
While uploading the Docs for my Crate, I noticed that I can't hide the `dylint_version()` Function inside the docs.
https://minersebas.github.io/bevy_lint/bevy_lint/index.html#functions
This adds the `#[doc(hidden)]` Attribute inside the `dylint_library!` Macro, to hide the function.
> Hide dylint_version() in docs

- dylint/src/lib.rs
> Fix "unreachable statement" warning on Windows

- cargo-dylint/tests/list.rs
- dylint/src/name_toolchain_map.rs
I thought 6c71daa was needed to enabled 1ad7da7, but that turned out not
to be the case. I may reenable 6c71daa after I have had more time to
think about what the "right" behavior should be.
> Revert 6c71daa

- dylint/src/package_options/mod.rs
`dylint-template` was [updated](https://github.com/trailofbits/dylint-template/pull/16) to use the [new macros](https://github.com/trailofbits/dylint/pull/284). But this, in turn, requires changes in the code that uses `dylint-template`.
> Adjust for template changes

- examples/restriction/const_path_join/README.md
`prettier`'s behavior seems to have changed. I think this may be why: https://github.com/prettier/prettier/pull/13155
> Fix `const_path_join` README

- README.md
- cargo-dylint/README.md
- dylint/README.md
The config name was changed in https://github.com/rust-lang/rust-analyzer/pull/12010
> Update rust-analyzer config name

- Cargo.lock
- examples/general/await_holding_span_guard/Cargo.lock
- examples/general/crate_wide_allow/Cargo.lock
- examples/general/env_cargo_path/Cargo.lock
- examples/general/non_local_effect_before_error_return/Cargo.lock
- examples/general/non_thread_safe_call_in_test/Cargo.lock
- examples/restriction/collapsible_unwrap/Cargo.lock
- examples/restriction/const_path_join/Cargo.lock
- examples/restriction/env_literal/Cargo.lock
- examples/restriction/inconsistent_qualification/Cargo.lock
- examples/restriction/misleading_variable_name/Cargo.lock
- examples/restriction/missing_doc_comment_openai/Cargo.lock
- examples/restriction/question_mark_in_expression/Cargo.lock
- examples/restriction/ref_aware_redundant_closure_for_method_calls/Cargo.lock
- examples/restriction/suboptimal_pattern/Cargo.lock
- examples/restriction/try_io_result/Cargo.lock
- examples/supplementary/overscoped_allow/Cargo.lock
- examples/supplementary/redundant_reference/Cargo.lock
- examples/supplementary/unnecessary_borrow_mut/Cargo.lock
- examples/supplementary/unnecessary_conversion_for_trait/Cargo.lock
- examples/testing/clippy/Cargo.lock
- examples/testing/straggler/Cargo.lock
- internal/Cargo.toml
The need for `dirs` went away with #604 (I think).
> Remove `dirs` dependency

- examples/restriction/misleading_variable_name/src/lib.rs
- examples/restriction/misleading_variable_name/ui/main.rs
Don't flag functions/types defined in the same module as the call.
> Fix bug in `misleading_variable_name`

- dylint/src/error.rs
- examples/restriction/derive_opportunity/src/lib.rs
- examples/restriction/inconsistent_qualification/src/lib.rs
- examples/restriction/inconsistent_qualification/ui/main.rs
- examples/restriction/inconsistent_qualification/ui/main.stderr
- internal/src/cargo.rs
- utils/testing/src/lib.rs
This PR fixes a false negative concerning use of local paths in `inconsistent_qualification`.
It also improves the generated error messages, particularly in regard to traits and modules.
> Fix false negative in `inconsistent_qualification`

- cargo-dylint/tests/markdown_link_check.json
They recently started returning 403s.
> Don't markdown-link-check OpenAI urls

- cargo-dylint/tests/dylint.rs
https://github.com/tcort/markdown-link-check/releases/tag/v3.11.2
> Unpin `markdown-link-check`

- dylint/src/metadata.rs
Rather than generate errors, when building metadata entries.
> Ignore subdirectories that do not contain packages

- dylint/Cargo.toml
- examples/general/Cargo.lock
- examples/restriction/assert_eq_arg_misordering/Cargo.lock
- examples/restriction/collapsible_unwrap/Cargo.lock
- examples/restriction/const_path_join/Cargo.lock
- examples/restriction/derive_opportunity/Cargo.lock
- examples/restriction/env_literal/Cargo.lock
- examples/restriction/inconsistent_qualification/Cargo.lock
- examples/restriction/misleading_variable_name/Cargo.lock
- examples/restriction/missing_doc_comment_openai/Cargo.lock
- examples/restriction/overscoped_allow/Cargo.lock
- examples/restriction/question_mark_in_expression/Cargo.lock
- examples/restriction/ref_aware_redundant_closure_for_method_calls/Cargo.lock
- examples/restriction/suboptimal_pattern/Cargo.lock
- examples/restriction/try_io_result/Cargo.lock
- examples/supplementary/Cargo.lock
- examples/testing/clippy/Cargo.lock
- examples/testing/straggler/Cargo.lock
#858 made `curl-sys` a non-optional dependency of the `dylint` package. This had unintended side effects, e.g., causing all of the example lints to transitively depend on `curl-sys`. The present PR rectifies the situation.
> Make `curl-sys` an optional dependency

- examples/general/Cargo.lock
- examples/general/non_local_effect_before_error_return/Cargo.toml
- examples/general/non_local_effect_before_error_return/src/lib.rs
- examples/general/non_local_effect_before_error_return/ui/main.rs
- examples/general/non_local_effect_before_error_return/ui/main.stderr
This PR adds the called function formatted string to the non-local-effect lint message. 
This allows knowing which function triggered the lint if the issue is in a derived/expanded function (e.g., in a structure declaration).
> Add function name to the non local effect lint

- cargo-dylint/tests/boundary_toolchains.rs
- cargo-dylint/tests/list.rs
- cargo-dylint/tests/package_options.rs
`cargo-platform v0.1.8` requires rustc 1.73 or newer.
> Update `boundary_toolchains` test

- examples/supplementary/commented_code/src/lib.rs
- examples/supplementary/commented_code/ui/main.rs
`commented_code` should not flag single identifiers.
This PR is just a placeholder until I produce a fix.
> Add `commented_code` false positive

- clippy.toml
- examples/experimental/missing_doc_comment_openai/src/lib.rs
- examples/general/non_local_effect_before_error_return/src/visit_error_paths.rs
- examples/general/non_thread_safe_call_in_test/src/late.rs
- examples/restriction/overscoped_allow/src/lib.rs
This is a [95% solution](https://github.com/trailofbits/dylint/issues/654#issuecomment-1849753754) to #654.
The 100% solution would be a custom lint.
> Make `DiagCtxt::warn` a disallowed method

- cargo-dylint/tests/supply_chain/cargo_lib/aarch64-apple-darwin.json
- cargo-dylint/tests/supply_chain/cargo_lib/x86_64-apple-darwin.json
- cargo-dylint/tests/supply_chain/cargo_lib/x86_64-pc-windows-msvc.json
- cargo-dylint/tests/supply_chain/cargo_lib/x86_64-unknown-linux-gnu.json
- dylint/src/driver_builder.rs
Recently, this seems to have become necessary to build drivers on macOS.
> Add `#![feature(rustc_private)]` to driver's main.rs

- Cargo.lock
- dylint/Cargo.toml
Ref:
- https://github.com/trailofbits/dylint/commit/80fb5229d88fc8de217b04ff24c5e704fabe332c
- https://github.com/trailofbits/dylint/commit/939cd8ca7f327f0dcce05a91a80ebc4153698952
> No longer rely on `curl-sys` directly

- internal/template/src/lib.rs
The crate was recently renamed: https://github.com/rust-lang/rust/pull/134381
> Remove `extern crate rustc_attr;` from template

- cargo-dylint/tests/ci.rs
- internal/Cargo.toml
- internal/src/home.rs
https://github.com/rust-lang/rust/pull/132515#discussion_r1829715262
> Allow `deprecated` for `std::env::home_dir`

- cargo-dylint/tests/ci.rs
- examples/experimental/derive_opportunity/Cargo.lock
- examples/experimental/missing_doc_comment_openai/Cargo.lock
- examples/experimental/overscoped_allow/Cargo.lock
- examples/general/Cargo.lock
- examples/restriction/Cargo.lock
- examples/supplementary/Cargo.lock
- examples/testing/clippy/Cargo.lock
- examples/testing/straggler/Cargo.lock
Reverts trailofbits/dylint#1410
This repo uses multiple, interdependent workspaces. One workspace could depend on a package from another, but the dependent's Cargo.lock file might not be up-to-date with respect to the latter's.
> Revert "Remove `update` test"

- cargo-dylint/src/main.rs
- dylint/src/opts.rs
- dylint/src/package_options/auto_correct/mod.rs
- dylint/src/package_options/mod.rs
I also have to handle path in 
```rust
pub fn auto_correct_revertible()
````
function.
Close #601 
@smoelius
> Make the path argument to optional

- examples/general/abs_home_path/README.md
- examples/general/abs_home_path/src/lib.rs
This PR implements the first part of issue #1358, making the `abs_home_path` lint smarter by not warning in build script contexts. Build scripts often need to reference absolute paths during the build process, making these warnings false positives.
- Added `rustc_session` to the extern crate declarations
- Added detection of build scripts in the `check_expr` method by checking if the crate name is "build_script_build"
- Skipped lint checking when in a build script context
The implementation follows Clippy's approach of checking the crate name to detect build scripts, as referenced in the issue.
I've verified the lint no longer triggers in build scripts by testing against the examples in the issue.
Resolves first part of #1358
> Don't warn about absolute home paths in build scripts

- examples/general/Cargo.lock
- examples/general/crate_wide_allow/Cargo.toml
- examples/general/crate_wide_allow/src/lib.rs
- internal/src/cargo.rs
- internal/src/testing.rs
From the doc comment:
```rs
/// Debug-builds `cargo-dylint` and returns a path to the resulting executable
///
/// Arguments
///
/// - `workspace_root`: path to workspace root
///
/// To run the executable from a test, the likely easiest way is to pass
/// `--path <PATH_TO_LIBRARY_PACKAGE>` or `--lib-path <PATH_TO_DYNAMIC_LIBRARY>`.
```
> Add `dylint_internal::testing::cargo_dylint`

- examples/general/non_local_effect_before_error_return/src/lib.rs
- examples/general/non_local_effect_before_error_return/ui/main.rs
- examples/general/non_local_effect_before_error_return/ui/main.stderr
- examples/general/non_local_effect_before_error_return/ui_public_only/main.rs
- examples/general/non_local_effect_before_error_return/ui_public_only/main.stderr
This PR addresses issue #929 by preventing the `non_local_effect_before_error_return` lint from firing in functions that return `std::fmt::Result`.
The lint was previously triggering warnings for functions returning `std::fmt::Result`, but as noted in the issue, these reports tend to be uninteresting and add unnecessary noise to the lint output.
1. Renamed the `is_result` function to `is_lintable_result` to better reflect its purpose
2. Enhanced the function to check if the second generic argument of `Result` is `core::fmt::Error`
3. If the error type is `core::fmt::Error`, the function now returns `false`, preventing the lint from being applied
4. Added test cases in both `ui/main.rs` and `ui_public_only/main.rs` to verify the behavior
The implementation follows the approach suggested in …
> Fix: Don't trigger lint for std::fmt::Result return types

- cargo-dylint/tests/ci.rs
- examples/README.md
This PR addresses #636 by replacing the bash script (`scripts/update_example_READMEs.sh`) with a Rust-based test that verifies the examples/README.md contents are in sync with the actual examples in the codebase.
The test:
- Walks through all example categories (general, supplementary, restriction, experimental, and testing)
- Extracts example names and descriptions from each Cargo.toml file
- Generates a temporary README.md with the expected content
- Verifies that the actual README.md contains all necessary example links and descriptions
This change makes the README verification process part of the standard test suite, runnable via `cargo test`. By keeping this verification in Rust rather than bash, we ensure better cross-platform compatibility and integration with the rest of the …
> Convert README verification script to a Rust test

- cargo-dylint/tests/ci.rs
Removed the Changelog link test from the markdown_link_check ci test as mentioned in #1604 
I tested it locally and the test passed locally
> Skip CHANGELOG.md in markdown link check to avoid GitHub rate limits

- .github/workflows/ci.yml
Since #1563, calling the script is no longer necessary.
> No longer call update_example_READMEs.sh in ci.yml

- cargo-dylint/tests/ci.rs
This PR updates the `markdown-link-check` tool used in CI tests by removing the version pinning that was implemented as a workaround for a previously reported issue.
The changes were tested to ensure it compiles successfully with the updated version. The latest version of `markdown-link-check` will now be used, which includes fixes for the previously encountered bug.
Fixes #1618
> Update markdown-link-check version in CI tests

- cargo-dylint/tests/ci.rs
Additional precaustions to avoid hitting GitHub rate limits
> Skip symlinks and add `--retry=1s` to `markdown_link_check` test

- docs/how_dylint_works.md
Remove duplication from library name and path descriptions
> docs: fix duplication in how_dylint_works

- examples/general/wrong_serialize_struct_arg/README.md
- examples/general/wrong_serialize_struct_arg/src/lib.rs
- examples/general/wrong_serialize_struct_arg/ui/main.rs
- examples/general/wrong_serialize_struct_arg/ui/main.stderr
- internal/src/paths.rs
This PR addresses #850 which basically enhances the `wrong_serialize_struct_arg` lint to apply to more Serde serialization functions.
The following Serde Serializer methods, in addition to the original serialize_struct are supported now:
- [serialize_struct_variant](https://docs.rs/serde/latest/serde/trait.Serializer.html#tymethod.serialize_struct_variant)
- [serialize_tuple](https://docs.rs/serde/latest/serde/trait.Serializer.html#tymethod.serialize_tuple)
- [serialize_tuple_struct](https://docs.rs/serde/latest/serde/trait.Serializer.html#tymethod.serialize_tuple_struct)
- [serialize_tuple_variant](https://docs.rs/serde/latest/serde/trait.Serializer.html#tymethod.serialize_tuple_variant)
> Enhance wrong_serialize_struct_arg lint to cover more Serde serialization methods

- dylint-link/src/main.rs
- internal/src/command.rs
Description:  
This pull request corrects minor typos in comments within the codebase to improve clarity and readability. Specifically, it fixes the spelling of "instead" and "successfully" in comments in `dylint-link/src/main.rs` and `internal/src/command.rs`. No functional code changes are included; only comment text has been updated.
> Fix Typos in Comments for Clarity

- cargo-dylint/tests/ci.rs
This PR solves #636 and introduces a new integration test `lint_script_test` to ensure that linting remains clean across various directories. The test replicates the functionality of the existing `lint.sh` script using Rust.
* Automates the execution of `cargo-dylint` across:
* `examples/general`
* `examples/supplementary`
* `examples/restriction` (excluding `overscoped_allow`)
* `examples/testing/clippy`
* Dynamically detected `examples/experimental` subdirectories
* Sets `DYLINT_RUSTFLAGS` to `-D warnings` to ensure strict linting
* Cleans up old `.fingerprint` directories under nightly targets to force fresh lint runs
* Asserts success of each lint command and logs output for debugging upon failure
Fixes #636
> Add: Converted `lint` test from workflow and added to rust rest

- .github/workflows/ci.yml
- cargo-dylint/tests/ci.rs
- cargo-dylint/tests/markdown_link_check.json
- internal/src/env.rs
This PR addresses the issue with `markdown_link_check` test failures caused by GitHub API rate limiting (429 errors). The test frequently fails when it encounters "Too Many Requests" responses from GitHub, preventing successful validation of markdown links.
1. Added `GITHUB_TOKEN` constant to `internal/src/env.rs` to reference the environment variable throughout the codebase.
2. Modified the `markdown_link_check` test in `cargo-dylint/tests/ci.rs` to:
- Skip the test when `GITHUB_TOKEN` is not set (with informative message)
- Create a dynamic config with the actual token for authentication when available
3. Updated `cargo-dylint/tests/markdown_link_check.json` to use GitHub token authentication for both github.com and api.github.com URLs
The implementation follows the approach suggested …
> Fix markdown_link_check test failures due to GitHub API rate limiting

- Cargo.lock
- examples/Cargo.toml
- examples/src/lib.rs
Relevant issue #1533 
This test ensures that all lints defined in the "general" and "supplementary" folders are actually registered in the corresponding src/lib.rs file. The process is as follows:
1. Extract expected lints by listing the immediate subdirectories in "general" and "supplementary" (ignoring src and hidden directories) to determine the expected lint module names.
2. Read the src/lib.rs file in both folder and extract registered lints using this regex 
`([a-zA-Z_][a-zA-Z0-9_]*)::register_lints\s*\(` which captures the module name right before the literal `::register_lints` call.
4. Lastly, compare the expected and actually registered lints.
if we were to run the test with the dylint's current state we would get this output:
```bash
---- verify_registered_lints stdout ---- …
```
> feat#1533: verify  `general` and `supplementary`  registered lints

- .github/workflows/ci.yml
rust-lang/cargo#15698 in Cargo 1.89.
> Revert 58691762b8cc77e2a575f24498c0b354296ef0da

- utils/linting/tests/build.rs
- utils/testing/src/lib.rs
- utils/testing/src/ui.rs
This way, there will be at most one attempt to build a driver. If that attempt fails, subsequent attempts will show the same failing result.
> Cache driver `Result` rather than `Path`
