examples/README.md, scripts/update_example_READMEs.sh
=> Display examples in a table

.github/workflows/update.yml
Addresses #36. Obviates #35 (I think).
=> GitHub action to update dependencies

README.md, examples/allow_clippy/Cargo.toml, examples/clippy/Cargo.toml, examples/env_literal/Cargo.toml, examples/path_separator_in_string_literal/Cargo.toml, examples/question_mark_in_expression/Cargo.toml, examples/try_io_result/Cargo.toml
This adds Documentation on how to get rust-analyzer working in a Lint library and adds the necessary Lines to all examples.
=> Rust analyzer

README.md
This runs dylint also on Benches, Examples and Tests.
=> In the VS Code Integration also include the --all-targets flag

utils/testing/README.md
=> Add instructions for updating .stderr files

cargo-dylint/src/main.rs, cargo-dylint/tests/fix.rs, cargo-dylint/tests/metadata.rs, cargo-dylint/tests/package_options.rs, cargo-dylint/tests/test_log.rs, dylint/src/lib.rs, examples/path_separator_in_string_literal/src/path_separator_in_string_literal.rs, examples/path_separator_in_string_literal/ui_non_windows/main.fixed, examples/path_separator_in_string_literal/ui_non_windows/main.rs, examples/path_separator_in_string_literal/ui_non_windows/main.stderr, examples/path_separator_in_string_literal/ui_windows/main.fixed, examples/path_separator_in_string_literal/ui_windows/main.rs, examples/path_separator_in_string_literal/ui_windows/main.stderr, internal/src/cargo.rs, internal/src/lib.rs, utils/testing/src/lib.rs
=> Add `--fix` option

cargo-dylint/tests/dylint.rs, cargo-dylint/tests/metadata.rs, dylint/src/metadata.rs, internal/src/cargo.rs, internal/src/lib.rs
=> Error when metadata entry names a nonexistent library

README.md, cargo-dylint/README.md, cargo-dylint/src/main.rs, cargo-dylint/tests/dylint.rs, cargo-dylint/tests/metadata.rs, driver/src/lib.rs, dylint-link/src/main.rs, dylint/README.md, dylint/src/driver_builder.rs, dylint/src/error.rs, dylint/src/lib.rs, dylint/src/name_toolchain_map.rs, examples/redundant_reference/src/lib.rs, internal/src/filename.rs, internal/src/lib.rs, scripts/check_licenses.sh, scripts/lint.sh
=> Set `--cfg=dylint_lib="..."` in driver

cargo-dylint/tests/package_options.rs
Account for https://github.com/rust-lang/libc/pull/2820
=> Fix `downgrade_upgrade_package` test

examples/general/non_local_effect_before_error_return/src/visit_error_paths.rs, examples/general/non_local_effect_before_error_return/ui/main.rs, examples/general/non_local_effect_before_error_return/ui/main.stderr
=> Fix 'assertion failed: elem.index() < self.domain_size'

utils/linting/src/lib.rs
Currently, `dylint_linting` chokes if run on a build.rs file in the workspace root.
=> Canonicalize `local_crate_source_file`

Cargo.lock, cargo-dylint/tests/metadata.rs, dylint/Cargo.toml, dylint/src/metadata.rs, dylint/src/toml.rs
=> Update `cargo` dependency

examples/supplementary/overscoped_allow/src/lib.rs
=> Cache canonicalized paths in `overscoped_allow`

cargo-dylint/tests/dylint.rs
This is needed because `npx markdown-link-check` is run from a temporary directory.
=> Use absolute paths in `markdown_link_check` test

Cargo.lock, dylint/Cargo.toml, examples/general/Cargo.lock, examples/restriction/assert_eq_arg_misordering/Cargo.lock, examples/restriction/collapsible_unwrap/Cargo.lock, examples/restriction/const_path_join/Cargo.lock, examples/restriction/derive_opportunity/Cargo.lock, examples/restriction/env_literal/Cargo.lock, examples/restriction/inconsistent_qualification/Cargo.lock, examples/restriction/misleading_variable_name/Cargo.lock, examples/restriction/missing_doc_comment_openai/Cargo.lock, examples/restriction/overscoped_allow/Cargo.lock, examples/restriction/question_mark_in_expression/Cargo.lock, examples/restriction/ref_aware_redundant_closure_for_method_calls/Cargo.lock, examples/restriction/suboptimal_pattern/Cargo.lock, examples/restriction/try_io_result/Cargo.lock, examples/supplementary/Cargo.lock, examples/testing/clippy/Cargo.lock, examples/testing/straggler/Cargo.lock
Workaround taken from here: https://github.com/alexcrichton/curl-rust/issues/524#issuecomment-1703325064
=> Work around curl/curl#11893

dylint/src/driver_builder.rs, dylint/src/metadata/cli/mod.rs, internal/src/cargo.rs, internal/src/command.rs, internal/src/rustup.rs, utils/testing/src/lib.rs
=> Attempt to fix #1007

cargo-dylint/src/main.rs, dylint/src/lib.rs
Remove README uses, but keep the option.
=> Revert parts of #1040

cargo-dylint/tests/boundary_toolchains.rs, cargo-dylint/tests/list.rs
Account for: https://github.com/serde-rs/serde/commit/8e6637a1e44c30dffd37322a7107d434cd751722
=> Update `boundary_toolchains` test

cargo-dylint/tests/ci.rs
I'm no longer convinced it provides value.
=> Remove `update` test

examples/src/lib.rs
https://github.com/trailofbits/dylint/issues/1417
=> test: expand `examples_do_not_have_gitignore` to check more files/paths

Cargo.toml, examples/general/Cargo.toml, examples/restriction/Cargo.toml, examples/supplementary/Cargo.toml, scripts/lint.sh
This allows lint.sh to be significantly simplified.
=> Specify lint levels in Cargo.toml files

examples/supplementary/nonexistent_path_in_comment/src/lib.rs, examples/supplementary/nonexistent_path_in_comment/ui/main.rs, examples/supplementary/nonexistent_path_in_comment/ui/main.stderr
=> Handle line and column references in `nonexistent_path_in_comment`

examples/restriction/suboptimal_pattern/ui/main.rs, examples/restriction/suboptimal_pattern/ui/main.stderr, examples/restriction/suboptimal_pattern/ui_no_explicit_deref_check/main.rs, examples/restriction/suboptimal_pattern/ui_no_explicit_deref_check/main.stderr
=> Fix formatting in restrictions/suboptimal_pattern

examples/src/lib.rs
This PR adds a new test in `examples/src/lib.rs` that verifies the formatting  of all `.rs` files in the examples directory using `rustfmt`. This ensures that all example files, including UI tests that are not part of a standard Cargo project, follow consistent formatting standards.
- Added a new `check_examples_formatting` test function that:
- Uses `walkdir` to recursively search the examples directory for `.rs` files
- Runs `rustfmt +nightly --check --edition=2024` on each file
- Reports any formatting failures
Verified that the test now passes after formatting was applied to all files.
Fixes #1616
=> test: Add formatting check for examples' UI tests

examples/restriction/try_io_result/src/lib.rs
The variable is a `LocalDefId`, not an `HirId`.
=> Correct variable name in `try_io_result`

README.md, cargo-dylint/README.md, dylint/README.md
The command was renamed. See https://github.com/rust-lang/rust-analyzer/pull/13799
=> Update Rust Analyzer override command in docs
